version: "3"
services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: ./climb-app-api
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/myapp"
    ports:
      - 3000:3000
    depends_on:
      - db
  vue:
    build: ./climb-app-vue
    ports:
      - 8080:8080
    command: sh -c "npm install && npm run serve"
    volumes:
      - ".:/app"
    depends_on:
      - web
